GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVGFyaWsiLCJpYXQiOjE2OTU2Nzc0NDB9._t7PNoXrDenKZsF88hp8KtB9de6OqwxPDDgK1B3DHuA
###

POST http://localhost:3000/login
Content-Type: application/json 

{
    "username": "Tarik"
}

###
GET http://localhost:3000/users
